---
title: 컴파일러 오류 CS0156
ms.date: 07/20/2015
f1_keywords:
- CS0156
helpviewer_keywords:
- CS0156
ms.assetid: 32026b1b-bcd7-4464-b63f-3b38c00452a6
ms.openlocfilehash: a660a2a4c27adc327777f8b05cd183ef58bd6343
ms.sourcegitcommit: 986f836f72ef10876878bd6217174e41464c145a
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 08/19/2019
ms.locfileid: "69604721"
---
# <a name="compiler-error-cs0156"></a>컴파일러 오류 CS0156
바로 바깥쪽 catch 절에 중첩된 finally 절에는 인수가 없는 throw 문을 사용할 수 없습니다.  
  
 매개 변수가 없는 [throw](../language-reference/keywords/throw.md) 문은 매개 변수를 사용하지 않는 **catch** 절에서만 나타날 수 있습니다.  
  
 자세한 내용은 [예외 및 예외 처리](../programming-guide/exceptions/index.md)를 참조 하세요.  
  
 다음 샘플에서는 CS0156을 생성합니다.  
  
```csharp  
// CS0156.cs  
using System;  
  
namespace MyNamespace  
{  
   public class MyClass2 : Exception  
   {  
   }  
  
   public class MyClass  
   {  
      public static void Main()  
      {  
         try  
         {  
            throw;   // CS0156  
         }  
  
         catch(MyClass2)  
         {  
            throw;   // this throw is valid  
         }  
      }  
   }  
}  
```
