---
title: "'Catch' 형식을 catch 할 수 없습니다 '<typename>' 'System.Exception' 또는 'System.Exception'에서 상속한 클래스가 아니므로"
ms.date: 07/20/2015
f1_keywords:
- vbc30392
- bc30392
helpviewer_keywords:
- BC30392
ms.assetid: 1d513d1d-38f5-4b4e-95bb-9f1209553803
ms.openlocfilehash: caf1b24e50d01efd017b40cf615eb1e541a44c9b
ms.sourcegitcommit: 9b552addadfb57fab0b9e7852ed4f1f1b8a42f8e
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 04/23/2019
ms.locfileid: "61931419"
---
# <a name="catch-cannot-catch-type-typename-because-it-is-not-systemexception-or-a-class-that-inherits-from-systemexception"></a>'Catch' 형식을 catch 할 수 없습니다 '\<typename >' 'System.Exception' 또는 'System.Exception'에서 상속한 클래스가 아니므로
`Catch` 는 예외를 가로챌 수만 있는데 예외에서 파생되지 않은 요소를 catch하려고 했습니다.  
  
 **오류 ID:** BC30392  
  
## <a name="to-correct-this-error"></a>이 오류를 해결하려면  
  
1. `Catch` 문을 제거하거나 `Catch` 의 대상을 실제 예외로 변경합니다.  
  
## <a name="see-also"></a>참고자료

- [Try...Catch...Finally 문](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
